apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "m2repo2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "hellotest"
spec:
  source:
    git:
      uri: "https://github.com/oceatt/oceattworkspace" 
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "hellotest/Jenkinsfile"