node {
        def app
    
        stage('Clone repository') {
            /* Let's make sure we have the repository cloned to our workspace */
            checkout scm
        }
    
    	
    	dir('exp-api-doc'){
        stage('Build image') {   
            app = docker.build "nginx"
        }
    
        stage('Push image') {
            
            docker.withRegistry('https://registry.hub.docker.com') {
                app.push("1")
                app.push("latest")
            }
        }
        }
}
